### ISSUE TITLE
Creating thumbnail failed

### ISSUE THREAD

**Issue by cuixiping** [picturama/picturama#38]
OS: Windows 7
Picturama: 1.1.0
Issue Description: Every picture shows "Creating thumbnail failed"

![image](https://user-images.githubusercontent.com/1104492/81905774-c9017c80-95f7-11ea-83b1-06785ec987cf.png)

**Comment by jackusay** [comment]
me too
a lot of warning and error in dev tool...

```sh
app.js:1 Getting thumbnail failed Unable to initialize WebGL. Your browser or machine may not support it.
(anonymous) @ app.js:1
/C:/Users/xxx/.picturama/thumbnails/4.webp?v=1589634468044:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
...
/C:/Users/xxx/.picturama/thumbnails/8.webp?v=1589634468044:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
/C:/Users/xxx/.picturama/thumbnails/c.webp?v=1589634468044:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
app.js:1 Getting thumbnail failed Unable to initialize WebGL. Your browser or machine may not support it.
(anonymous) @ app.js:1
...
app.js:1 Getting thumbnail failed Unable to initialize WebGL. Your browser or machine may not support it.
(anonymous) @ app.js:1
```

**Comment by til-schneider** [comment]
This error means, that your computer has no 3D acceleration activated. So either your graphic card doesn't support 3D acceleration or it is not activated (some laptops do this in order to increase battery time).

Picturama needs 3D acceleration in order to function. So you either have to turn it on or it just doesn't work on this computer.

Picturama should show a better error message in this case.
