### ISSUE TITLE
Why not use ipcRenderer.invoke?

### ISSUE THREAD

**Issue by bammoo** [picturama/picturama#84]
It's easier to handle ipc https://www.electronjs.org/docs/api/ipc-renderer#ipcrendererinvokechannel-args

**Comment by til-schneider** [comment]
Can you provide a little bit of context?

**Comment by bammoo** [comment]
Electron provide `ipcRenderer.invoke` which I think is better than `ipcRenderer.send`   

code refference: https://github.com/picturama/picturama/blob/master/src/app/BackgroundClient.ts#L181

**Comment by til-schneider** [comment]
Why is it better? I see no difference in using `ipcRenderer.invoke` compared to `ipcRenderer.send` and `webContents.send`. Since there is no `webContents.invoke` and I need both directions (renderer calls background and background calls foreground), I prefer a symmetric implementation in `BackgroundClient` / `BackgroundService` and `ForegroundClient` / `ForegroundService`.
